name       : python-bleach
version    : 4.0.0
release    : 10
source     :
    - https://github.com/mozilla/bleach/archive/refs/tags/v4.0.0.tar.gz : 10fcaf8c3d1b7ea1bf4ea7d52fc48f0f40d83dc62ae4580bb60daae4a5190e11
homepage   : https://github.com/mozilla/bleach
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - pkgconfig(python3)
    - python-genshi
    - python-lxml
    - python-packaging
    - python-pytest
    - python-webencodings
rundeps    :
    - python-packaging
    - python-six
    - python-webencodings
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not test_uri_value_allowed_protocols'
