name       : python-bleach
version    : 3.2.1
release    : 8
source     :
    - https://github.com/mozilla/bleach/archive/v3.2.1.tar.gz : aa80c990c597d27144d9148bdba4b1752f70a6efe0e8b8c4451b7aef464d544b
homepage   : https://github.com/mozilla/bleach
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - pkgconfig(python3)
    - python-genshi
    - python-lxml
    - python-packaging
    - python-pytest
    - python-webencodings
rundeps    :
    - python-packaging
    - python-six
    - python-webencodings
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
