name       : python-bleach
version    : '2.0'
release    : 1
source     :
    - https://github.com/mozilla/bleach/archive/v2.0.tar.gz : 789dcf3e7daf79c4c78518c6ebafd51bbaf111ac4263a97c08cf8d6a27eda820
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-html5lib
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
