name       : python-bleach
version    : 2.1.2
release    : 3
source     :
    - https://github.com/mozilla/bleach/archive/v2.1.2.tar.gz : 87f02294a2d433bf0855f3b847611ed0f645808d647477797247462c49ec786d
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-html5lib
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
