name       : python-bleach
version    : 6.0.0
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/b/bleach/bleach-6.0.0.tar.gz : 1a1a85c1595e07d8db14c5f09f09e6433502c51c595970edc090551f0db99414
homepage   : https://github.com/mozilla/bleach
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - python-pytest       # check
    - python-webencodings # check
rundeps    :
    - python-six
    - python-tinycss2
    - python-webencodings
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
