name       : python-bleach
version    : 2.1.3
release    : 7
source     :
    - https://github.com/mozilla/bleach/archive/v2.1.3.tar.gz : 2efa88ba7a17032436f1e1d337601a6b6551ed734da21a39a53f5bee543ea2de
homepage   : https://github.com/mozilla/bleach
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes
    or strips markup and attributes.
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-html5lib
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
