name       : python-bleach
version    : 4.1.0
release    : 11
source     :
    - https://github.com/mozilla/bleach/archive/refs/tags/v4.1.0.tar.gz : 802ce1f635fa2d14669a6d87a9897ece4683feeaefe3fcc98afa9275502c03f9
homepage   : https://github.com/mozilla/bleach
license    : Apache-2.0
component  : programming.python
summary    : Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes
description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or strips markup and attributes.
builddeps  :
    - pkgconfig(python3)
    - python-genshi
    - python-lxml
    - python-packaging
    - python-pytest
    - python-webencodings
rundeps    :
    - python-packaging
    - python-six
    - python-webencodings
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not test_uri_value_allowed_protocols'
